### ISSUE TITLE
[date-range-picker] pressing "t" key while end date is focused resets value

### ISSUE THREAD

**Issue by DRiFTy17** [tyler-technologies-oss/forge#139]
**Describe the bug:**
With the date picker and date range picker, the user can hit ‘t' to select the current date. However, in the date range picker, if the user has the end date field active, hitting the 't’ button fills in the start date field instead of the end date field.

Original Jira issue reported here:
https://tylerjira.tylertech.com/browse/TCPSD-6392

**To Reproduce:**
1. Open calendar in date-range-picker
2. Focus end date
3. Press "t" key
4. Start date is filled in, not end date.

**Expected behavior:**
Keyboard interactions should be contextual with the `<input>` that is currently focused. End date should be populated with current date when pressing "t" key.

**Please complete the following information:**
 - Forge version: ^2.0.0
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Additional context:**
Currently all keyboard interaction pertains to the "start" `<input>`.

**Comment by Lillious** [comment]
Just for additional context, there was also no check for invalid (negative) date ranges which was causing another issue.
