### ISSUE TITLE
[file-picker] Helper text styling and area present even when there is no helper text

### ISSUE THREAD

**Issue by CrashBrennan** [tyler-technologies-oss/forge#140]
**Describe the bug:**
Even if there is no helper text, the helper text box still appears under the file picker.  This causes layout and styling issues for pages it is used in.  This issue is present (though not disruptive) on the storybook example.  

The helper text also appears to be outside the bounds of the height assigned to the file picker, causing it to shift layouts when present.

**To Reproduce:**
1. Go to ['forge wiki page for file picker'](https://forge.tylerdev.io/main/?path=/story/components-file-picker--default)
2. Right click on file picker and click inspect element
3. Navigate to the shadow root of the file picker
4. Mouse over The div with part="helper-text-container"
5. See that it is present in the layout despite there being no text.

**Expected behavior:**
The helper text box should not be present in the layout if there is no helper text.

**Screenshots:**
Here, the helper text area is present despite the absence of helper text, and it is placed in addition to the area assigned to the file picker, causing unwanted scrolling.
![image](https://user-images.githubusercontent.com/102050559/189757517-49deb20d-55ec-4c8f-9967-25703a25d969.png)

**Please complete the following information:**
 - Forge version: 2.4.0
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: Desktop
 - OS: Windows

**Comment by RobJacobs** [comment]
I think the culprit is this css rule
```
.forge-file-picker__helper-text::before {
    display: inline-block;
    width: 0;
    height: 16px;
    content: "";
    vertical-align: 0;
}
```
Which I believe comes from the helper-text mixin include [here](https://github.com/tyler-technologies-oss/forge/blob/main/src/lib/file-picker/_mixins.scss#L142) which in turn includes [this](https://github.com/tyler-technologies-oss/forge/blob/main/src/lib/field/_base.scss#L465) mixin from material/mixin/_typography and looks like 
```
/// Creates a baseline strut from the top of a container. This mixin is for
/// advanced users, prefer `baseline()`.
///
/// @param {Number} $distance - The distance from the top of the container to
///     the text's baseline.
@mixin baseline-top($distance, $query: feature-targeting.all()) {
  $feat-structure: feature-targeting.create-target($query, structure);

  &::before {
    @include feature-targeting.targets($feat-structure) {
      @include baseline-strut_($distance);

      vertical-align: 0;
    }
  }
}
```
As a work around use
```
forge-file-picker::part(helper-text-container) {
  display: none:
}
```
