### ISSUE TITLE
Visual Studio SaSS Web Compiler generates Empty CSS

### ISSUE THREAD

**Issue by webgurumike** [tyler-technologies-oss/forge#240]
**Describe the bug:**
When using Visual Studio's Web Compiler Extension from https://github.com/failwyn/WebCompiler, the generated CSS file is empty. 

**To Reproduce:**
1. Create new .Net 7 web application project
2. Install Tyler Forge from https://github.com/tyler-technologies-oss/forge using Package Manager console
3. The @tylertech modules will be added to "node_modules" directory outside of the project root.
4. Create app.scss file as starting point. Right-click > Web Compiler > Compile file.
5. Open generated compilerconfig.json file in the root, add the following to the config: "options": { "loadPaths": "../node_modules" }.
7. Within app.scss, add @use statements to import required Tyler Forge modules
```
@use '@tylertech/forge/styles/theme' as forge-theme;
@use '@tylertech/forge/styles/typography' as forge-typography;
```
8. Save the file. It should compile without error and generate the compiled output file.
9. Open the output file to see results.

**Expected behavior:**
Currently, the output file contains only the copyright comments from the theme, typography modules, and their dependencies. The rest is blank.

**Screenshots:**
**app.scss:**
![image](https://user-images.githubusercontent.com/1033597/221037708-d19e84ab-f92a-4e79-a1d6-e0c856b3df57.png)

**compilerconfig.json:**
![image](https://user-images.githubusercontent.com/1033597/221037814-edcb4b6e-6e32-46a4-a39f-057f734f7546.png)

**CSS output:**
![image](https://user-images.githubusercontent.com/1033597/221038094-3c13a28d-b8c8-420f-9c9d-993afa4bd0ff.png)

**Please complete the following information:**
 - Forge version: 2.13.2
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: Windows

**Additional context:**
I have also tried to replicate this using the Sass command-line interface (instead of Web Compiler) with the same results:
`> sass --load-path="C:\path\to\node_modules" "C:\path\to\project\root\wwwroot\css\sass\app.scss" "C:\path\to\project\root\wwwroot\css\sass\output.css"`

**Comment by michael-karr** [comment]
@DRiFTy17 - Yep, that was it. Not sure exactly where I got the lines I was using, but was from one of the documentation pages somewhere. Thanks!

**Comment by DRiFTy17** [comment]
Glad you're all set now. I'll make a note to tighten up our docs on this to be more clear.

Closing this issue, but let us know if you have any further issues.
