### ISSUE TITLE
upgrade to Storybook 7.x

### ISSUE THREAD

**Issue by DRiFTy17** [tyler-technologies-oss/forge#248]
In release candidate status at time of writing:
https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.0

**Comment by MikeMatusz** [comment]
Update: 7.0 has been officially released.
https://github.com/storybookjs/storybook/releases/tag/v7.0.2

**Comment by DRiFTy17** [comment]
Upgrade to Storybook v8
