### ISSUE TITLE
User theme icon state not synced on first load or page refresh

### ISSUE THREAD

**Issue by Lillious** [tyler-technologies-oss/forge#296]
**Describe the bug:**
When first loading or refreshing the page via a local vite session, the theme toggle icon will always reflect the toggle dark mode theme icon (moon). Once clicked, it will reflect the correct theme icon state until the page is refreshed.

1. Start a local vite session
2. Toggle the theme at the top right
3. Refresh the page

Expected behavior:
The Dark mode / Light mode icon state should reflect the correct viewing state upon loading the site for the first time or refreshing the page.

**Screenshots:**
![image](https://user-images.githubusercontent.com/107406373/236327235-ff2b9a70-46f3-4239-84af-58badf6f8f83.png)
![image](https://user-images.githubusercontent.com/107406373/236327281-d4dc1fdf-f7aa-46b6-979e-09828b18d8dd.png)

**Please complete the following information:**
 - Forge version: v2.13.2
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Comment by DRiFTy17** [comment]
Closing. Fixed in 829e44c
