### ISSUE TITLE
[Dialog] Moveable property disallows title text selection

### ISSUE THREAD

**Issue by Lillious** [tyler-technologies-oss/forge#304]
**Describe the bug:**
When enabling ``forge-dialog--moveable`` on a ``<forge-dialog>`` window, it prevents the title text from being selectable despite it having the selectable mouse icon.

**To Reproduce:**
1. Create a ``<forge-dialog>`` element with ``forge-dialog--moveable``
2. Attempt to text highlight the title

**Expected behavior:**
Child elements should not inherit the draggability of the parent element.

**Please complete the following information:**
 - Forge version: v2.13.2
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Additional context:**
Possible solutions:
- Allow the use of Alt + mouse down similar to the default browser functionality for selecting link text.
- Disallow child elements from inheriting the draggability of the parent element.
- Provide design guidance so developers can put a visual handle element that indicates the draggability.

**Comment by DRiFTy17** [comment]
This is fixed in 3.0
