### ISSUE TITLE
[Busy Indicator] Progress bar overlaps cancel button while in column layout

### ISSUE THREAD

**Issue by Lillious** [tyler-technologies-oss/forge#305]
**Describe the bug:**
When using the Busy Indicator component with the progress bar and cancel options both enabled while the layout mode is set to column, the progress bar will overlap onto the cancel button.

**To Reproduce:**
1. Create a busy indicator.
2. Set the layout to column.
3. Enable the cancel button and progress bar options.
4. Observe the cancel button underneath the progress bar.

**Expected behavior:**
There should be adequate space between the two elements that prevents overlapping.

![image](https://github.com/tyler-technologies-oss/forge/assets/107406373/061fdff3-4ef3-4374-a7e6-4cee331e2ccf)

**Please complete the following information:**
 - Forge version: v2.13.2
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Comment by DRiFTy17** [comment]
Closing as this component has been removed from the library in 3.0 and is now being migrated to the forge-extended repo where this will likely be fixed.
