### ISSUE TITLE
Feature Request: Mapping Component

### ISSUE THREAD

**Issue by MikeMatusz** [tyler-technologies-oss/forge#356]
Not so much as part of the core Forge repository, but it would be nice to have a centralized ESRI-based mapping component.  Tyler Spatial currently has something like this, but it's based on the 3.x ArcGIS API with is [EOL on July 1, 2024](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/), and also uses TCW 1.x instead of Forge 2.0.  There may already be plans/efforts to update it.  Tyler Public Safety has a 4.x implementation (not Forge-based), but an relatively early version of 4.x, and would require some heavy lifting to get it updated and decoupled from the application. 

The ArcGIS JavaScript API and the Dojo Toolkit dependencies require specialized knowledge, and it would be beneficial to centralize this component, rather than internally develop multiple variations on it.  Would also benefit maintenance and support of the component.

**Describe the component:**
Most likely in a satellite repository, provide a map view with configuration and/or composable components to meet the requirements of various divisions.

**Describe the use case:**
Some examples:
- Data visualization: plotting one or many points on a map (with clustering if necessary), heat maps
- Address verification: helping resolve a multi-match intersection (e.g. horseshoe shaped road) or lat/long to address
- Routing
- Viewing/updating details of points in a layer (e.g. Fire Hydrants)

**Required features:**
* Plot an arbitrary data source on the map.
* Inspect plotted points for additional details, handling multiple points at the same location.
* Display a heat map based on a data source of points.
* Toggle layers on and off
* Select layers from the map
* Draw arbitrary shapes on the map and get coordinates. 
* Search/inspect map features
Potentially more, will require more discussions to define fully.

**Nice-to-have features:**
Will require more discussions to define.

**Screenshots:**
Can be provided on request.

**Please complete the following information:**
 - Will this be a contribution by you or your team? Probably a collaborative effort.
 - What platforms will this component be used on? all
 - Does this component require a responsive design? Y
 - I have searched existing issues before creating this request? Y

**Additional context:**
Creating this as a tracking issue based on a Frontend Governance Board discussion.

**Comment by DRiFTy17** [comment]
Just to add to this, I do know that the spatial team is currently in progress upgrading their mapping component to the 4.0 API, as well as upgrading Forge 2.x at the same time. I'm fairly certain it already supports a number of the features outlined above, and I hope with the new changes that it becomes more lightweight.

I don't have much more information other than that, but it may be worth meeting with them to discuss any other needs they may not be aware of as well.

**Comment by DRiFTy17** [comment]
This will not be part of the core/atomic component library. It may make sense as a separate library within the awesome-forge ecosystem, but work has continued with the spatial team.
