### ISSUE TITLE
[tooltip] default the text size to something larger

### ISSUE THREAD

**Issue by Ross-Blakeney** [tyler-technologies-oss/forge#363]
**Describe the feature:**
Default the tooltip text size to something larger than it does today.

**Describe any alternatives you've considered:**
This can be done on an use-by-use basis. However, if it is determined that the current default is too small for general use then let's address here.

**Additional context:**
![image](https://github.com/tyler-technologies-oss/forge/assets/43068700/8f4765b9-66fd-4ac5-8790-ac858427eab7)
Seems a little difficult to read.
@jayexprs @nickonometry @Voltali

**Comment by DRiFTy17** [comment]
New 3.0 design take care of this
