### ISSUE TITLE
[Paginator]  Pagination buttons highlighted when disabled

### ISSUE THREAD

**Issue by taramagill** [tyler-technologies-oss/forge#474]
**Describe the bug:**
The 'Go to next page' and 'Go to last page' buttons are disabled, yet highlighted when there aren't enough records to warrant the buttons active (no second page).

This issue seems to be happening on page load only. For example, On Page load, when the table has 17 items and Rows per page is selected is 10 by default(which is total items are greater than default Rows per page selection). User selects 20 from the Rows per page drop down then we are seeing this issue. This issue doesn't appear after consequent changes of Rows per page.

**To Reproduce:**
1. Set 'Rows per page' to 50 when less than 50 records
2. 'Go to next page' and 'Go to last page' buttons are disabled, yet highlighted
3. Set 'Rows per page' to 10
4. 'Go to next page' and 'Go to last page' buttons are no longer highlighted and can be clicked

**Expected behavior:**
Buttons are disabled but not highlighted.

**Screenshots:**
![image](https://github.com/tyler-technologies-oss/forge/assets/108025668/386ffd3e-b675-4345-80ef-2d7cb09daace)

**Please complete the following information:**
 - Forge version: 2.19.1
 - I have searched existing issues before creating this report? [Y/N] Y
 - Browser: Chrome
 - Platform: desktop
 - OS: Windows

**Additional context:**

**Comment by MohsinMalik2** [comment]
@taramagill The attached SS isn't clear enough to understand the issue.

**Comment by taramagill** [comment]
![image](https://github.com/tyler-technologies-oss/forge/assets/108025668/7526d881-4760-416b-9f13-3d86731784ca)

Is this clearer?   Notice the two navigation buttons that are disabled are also highlighted.
There are only 12 out of 100 items so the buttons navigating to the right should be disabled.

**Comment by MohsinMalik2** [comment]
Yes! This one seems fine. I've understood the issue and will try to resolve it ASAP.

**Comment by DRiFTy17** [comment]
Have you validated that this is still an issue in the latest version?

I ask because I recently made some adjustments around this problem in version `2.21.2` noted in the release notes [here](https://github.com/tyler-technologies-oss/forge/releases/tag/v2.21.2).

**Comment by DRiFTy17** [comment]
Ok, I will go ahead and close this issue but feel free to reopen and tag me if you run into it again.
