### ISSUE TITLE
[forge-label-value] Single line attribute does not change the component.

### ISSUE THREAD

**Issue by Alex-Oxthorn** [tyler-technologies-oss/forge#493]
**Describe the bug:*

There's a regression with the forge-label-value's single line attribute. There is no visible change to the label value when this attribute is added or bound. Confirmed that it does not work on the forge storybook instance as well.

**Expected behavior:**
For it to become one line  when applied.

**Please complete the following information:**
 - Forge version: [v2.21.1]
 - I have searched existing issues before creating this report? [Y]
 - Browser: [only tested on Chrome, but presumably this applies to all.]
 - Platform: [All]
 - OS: [All]

**Comment by DRiFTy17** [comment]
This should be fixed in 3.0. Feel free to reopen is you find otherwise.
