### ISSUE TITLE
[components-autocomplete--default] Search term disappeared from Autocomplete input field when switching browser tabs.

### ISSUE THREAD

**Issue by rafiqdeen** [tyler-technologies-oss/forge#515]
**Describe the bug:**
When Searching any term in Autocomplete input field then switching browser tabs causing the input term disappeared.

**To Reproduce:**
1. Go to https://forge.tylerdev.io/main/?path=/docs/components-autocomplete--default
2. Click on "Choose State" AutoComplete input field and Enter the text "xyz".
3. When switch to next tab in Same browser and came back to Auto Complete forge tyler component tab.
4. Then the term "xyz" disappeared.

**Expected behavior:**
Can we preserve the input field text?

**Screenshots:**
![Screenshot from 2024-04-01 12-53-34](https://github.com/tyler-technologies-oss/forge/assets/9208269/aee526f2-c01d-453c-9324-3a0a1882d1f5)

**Please complete the following information:**
 - Forge version: [e.g. v2.0.0]
 - I have searched existing issues before creating this report? [Y/N]
 - Browser: [e.g. Chrome, Firefox, Safari, All]
 - Platform: [e.g. desktop, mobile, All]
 - OS: [e.g. Windows, Mac, Linux, iOS, Android, All]

**Comment by DRiFTy17** [comment]
@rafiqdeen The autocomplete has an `allowUnmatched` property that can be applied to preserve any text after the input is blurred (the field is being blurred when you switch browser tabs). This should be what you're looking for. I'll go ahead and close this, but let me know if we need to reopen.
