### ISSUE TITLE
[TextFieldComponentDelegate] Duplicate id value on forge-text-field and input element

### ISSUE THREAD

**Issue by RobJacobs** [tyler-technologies-oss/forge#729]
**Describe the bug:**
Duplicate id attribute value on the forge-text-field and input element when using the options id property

**To Reproduce:**
1. Create a `new TextFieldComponentDelegate({ options: { label: 'Label', id: 'text-field--id' })`
2. Notice the duplicate id's in rendered content.

**Expected behavior:**
Id attribute would only get added to the input element so label linking works correctly.

**Please complete the following information:**
 - Forge version: 3.3.1
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Additional context:**
Would be nice:
1. Be able to add attributes to the input element
2. If no id is supplied, autogenerate so the input label linking works out of the box.

**Comment by DRiFTy17** [comment]
I opened a PR to fix this specific issue, but in regards to the nice-to-haves you mentioned I chose not to include those, at least for right now.

> 1. Be able to add attributes to the input element

The input element is already exposed through the instance, so you can use the delegate to add extra attributes through the API. I want to try to keep configuration to the necessities on these...

> 2. If no id is supplied, autogenerate so the input label linking works out of the box.

I understand that this may be convenient, but at the same time it kind of hides the underlying issue of not linking these two elements together explicitly with a name that makes sense within the context of the application it's used in. I'm open to adding this, but let's discuss pros/cons in more detail and potentially include that in a separate change if we decide to move forward with it.
