### ISSUE TITLE
[chip-field] Popover icon disappears when the field is small and a selection is made

### ISSUE THREAD

**Issue by klschwartz** [tyler-technologies-oss/forge#749]
**Describe the bug:**
The popover icon at the end of the chip field disappears when at least one item is selected and the field width is small.

**To Reproduce:**
1. Enter a value in a chip field with a popover icon
2. Make your window smaller, or reduce the width of the field, or zoom your window in significantly.

See: https://forge.tylerdev.io/main/?path=/story/components-chip-field--demo&args=popoverIcon:!true

**Expected behavior:**
The icon should be visible.

**Screenshots:**
![image](https://github.com/user-attachments/assets/efde2634-2f47-4e20-82a7-381ff9a5a61c)

**Please complete the following information:**
 - Forge version: 3.3.5
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Comment by MikeMatusz** [comment]
I think this may just need a `min-width: 0;` on the `part="input"` in the field to prevent the input from auto-sizing larger than the available space.  Haven't played around with it much, there may be other considerations needed, but that definitely helps.
