### ISSUE TITLE
[autocomplete] Autocomplete starts open then quickly closes after it or its field is hidden then shown

### ISSUE THREAD

**Issue by klschwartz** [tyler-technologies-oss/forge#755]
**Describe the bug:**
If the autocomplete component or its field is hidden while the dropdown is open, when it is shown again, the dropdown from before the hide will quickly be shown then hidden.

**To Reproduce:**
1. Open the dropdown on an autocomplete
2. Hide the autocomplete or its field (can add 'hidden' in devtools)
3. Show the autocomplete again

**Expected behavior:**
The dropdown from before the hide will not be shown again.

**Please complete the following information:**
 - Forge version: 3.3.5
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: All
 - OS: All

**Comment by klschwartz** [comment]
@DRiFTy17 This issue was fixed for Chrome with your PR, but still exists in Firefox

**Comment by DRiFTy17** [comment]
@klschwartz I just created #765 with a fix for this, which is more reliable across browsers anyway. Thanks.
